In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'C:\Users\Alisher\Desktop\ddf.csv')

In [3]:
df.head()

,Unnamed: 0,Date,Time,ISIN,Isu_Name,Security_Type,Market,BRD_ID,Trade_Price,Trading_Volumn,Trading_Value
0,0,2016-09-19,10:02:00,UZ7055450009 BSEZ,ChEII <Bektemir-spirt eksperimental zavodi> AJ,CommonStock,STK,G1,500.0,126000,6.300000e+07
1,0,2016-09-20,10:02:00,UZ7014810004 UKPS,<O'zkimyopolimersavdo> aksiyadorlik jamiyati,CommonStock,STK,G1,2380.0,14213,3.382694e+07
2,0,2016-09-26,11:19:40,UZ7007130006 A007130,<Elektrqishloqqurilish> AJ,CommonStock,STK,NC,10000.0,40,4.000000e+05
3,0,2016-09-27,13:05:47,UZ7037610001 SVDB,AT <Savdogarbank>,CommonStock,STK,G1,100.0,20000000,2.000000e+09
4,1,2016-09-27,13:05:47,UZ7037610001 SVDB,AT <Savdogarbank>,CommonStock,STK,G1,100.0,29000000,2.900000e+09

In [4]:
df = df.drop('Unnamed: 0', axis=1)
df['Date'] = pd.to_datetime(df['Date'])
lastp = df.drop_duplicates(subset = 'ISIN', keep="last")
lastp.head()

,Date,Time,ISIN,Isu_Name,Security_Type,Market,BRD_ID,Trade_Price,Trading_Volumn,Trading_Value
22,2016-10-03,12:05:22,UZ7023950007 NICT,<Neft va gaz ishlab chiqarishni ta''mirlash> AJ,NaN,FCT,T1,8.3,21258,176441.4
28,2016-10-03,10:34:40,UZ7031150004 UMBP,<Buxoro paxta> AJ,CommonStock,STK,G1,1000.0,48804,48804000.0
60,2016-10-07,12:08:51,UZ7055870008 ORFB,<Orient Finans> XATB,CommonStock,STK,G1,1250.0,1600,2000000.0
127,2016-10-20,12:08:52,UZ7048090003 SVKK,Sirdaryo viloyat <Agrokimyohimoya> HAJ,CommonStock,STK,NC,1050.0,1400,1470000.0
132,2016-10-21,15:02:00,UZ7012440002 UREK,<Urganch ekskavator> AJ,CommonStock,STK,G1,5000.0,110,550000.0

In [5]:
lastp.shape

(192, 10)

In [6]:
issdf = pd.DataFrame()  # create empty ndf
allURL = 'https://uzse.uz/isu_infos?begin_date=01.04.1994&end_date=02.02.2019&locale=en&page=%d'
for k in range(1, 5):
    url = allURL % k
    if pd.read_html(url)[0].empty:
        break
    else:
        chunk = pd.read_html(url)[0]
        issdf = pd.concat([issdf, chunk])

issdf.head()

,#,Logo,Category,Ticker,ISIN,Isu Name,Listing Date,Currency,Parval,No. of ListingShares,Current Price
0,1,NaN,A,HMKB,UZ7011340005,<Hamkorbank> ATB,2007-02-06,UZS,5.0,19803920573,Показать
1,2,NaN,A,IPKY,UZ7039920002,AITB <Ipak Yo'li>,2007-02-22,UZS,10.0,28098500000,Показать
2,3,NaN,A,KPBA,UZ7047440001,<Kapitalbank> ATB,2007-04-04,UZS,950.0,101179000,Показать
3,4,NaN,A,TNBN,UZ7035530003,<Turonbank> ATB,2007-10-25,UZS,1700.0,445244882,Показать
4,5,NaN,A,TRSB,UZ7033480003,<Trastbank> XAB,2007-11-26,UZS,1000.0,160227000,Показать

In [7]:
nissdf = issdf.drop([' # ', 'Logo', 'Current Price'], axis = 1)
nissdf.head()

,Category,Ticker,ISIN,Isu Name,Listing Date,Currency,Parval,No. of ListingShares
0,A,HMKB,UZ7011340005,<Hamkorbank> ATB,2007-02-06,UZS,5.0,19803920573
1,A,IPKY,UZ7039920002,AITB <Ipak Yo'li>,2007-02-22,UZS,10.0,28098500000
2,A,KPBA,UZ7047440001,<Kapitalbank> ATB,2007-04-04,UZS,950.0,101179000
3,A,TNBN,UZ7035530003,<Turonbank> ATB,2007-10-25,UZS,1700.0,445244882
4,A,TRSB,UZ7033480003,<Trastbank> XAB,2007-11-26,UZS,1000.0,160227000

In [8]:
nissdf.dtypes

\n        Category\n                 object
\n\t\tTicker\n\t                     object
\n        ISIN\n                     object
\n        Isu Name\n                 object
\n          Listing Date\n           object
Currency                             object
Parval                              float64
No. of ListingShares                  int64
dtype: object

In [9]:
cols = ['Category','Ticker','ISIN', 'Isu_Name', 'Listing_Date', 'Currency', 'Par_Value', 'Listed_Quantity']
nissdf.columns = cols
nissdf.head()

,Category,Ticker,ISIN,Isu_Name,Listing_Date,Currency,Par_Value,Listed_Quantity
0,A,HMKB,UZ7011340005,<Hamkorbank> ATB,2007-02-06,UZS,5.0,19803920573
1,A,IPKY,UZ7039920002,AITB <Ipak Yo'li>,2007-02-22,UZS,10.0,28098500000
2,A,KPBA,UZ7047440001,<Kapitalbank> ATB,2007-04-04,UZS,950.0,101179000
3,A,TNBN,UZ7035530003,<Turonbank> ATB,2007-10-25,UZS,1700.0,445244882
4,A,TRSB,UZ7033480003,<Trastbank> XAB,2007-11-26,UZS,1000.0,160227000

In [10]:
nissdf['ISIN'] = nissdf['ISIN'] + ' ' + nissdf['Ticker']
nissdf.head()

,Category,Ticker,ISIN,Isu_Name,Listing_Date,Currency,Par_Value,Listed_Quantity
0,A,HMKB,UZ7011340005 HMKB,<Hamkorbank> ATB,2007-02-06,UZS,5.0,19803920573
1,A,IPKY,UZ7039920002 IPKY,AITB <Ipak Yo'li>,2007-02-22,UZS,10.0,28098500000
2,A,KPBA,UZ7047440001 KPBA,<Kapitalbank> ATB,2007-04-04,UZS,950.0,101179000
3,A,TNBN,UZ7035530003 TNBN,<Turonbank> ATB,2007-10-25,UZS,1700.0,445244882
4,A,TRSB,UZ7033480003 TRSB,<Trastbank> XAB,2007-11-26,UZS,1000.0,160227000

In [11]:
lastp = lastp.replace('  ',' ', regex=True)
lastp.head()

,Date,Time,ISIN,Isu_Name,Security_Type,Market,BRD_ID,Trade_Price,Trading_Volumn,Trading_Value
22,2016-10-03,12:05:22,UZ7023950007 NICT,<Neft va gaz ishlab chiqarishni ta''mirlash> AJ,NaN,FCT,T1,8.3,21258,176441.4
28,2016-10-03,10:34:40,UZ7031150004 UMBP,<Buxoro paxta> AJ,CommonStock,STK,G1,1000.0,48804,48804000.0
60,2016-10-07,12:08:51,UZ7055870008 ORFB,<Orient Finans> XATB,CommonStock,STK,G1,1250.0,1600,2000000.0
127,2016-10-20,12:08:52,UZ7048090003 SVKK,Sirdaryo viloyat <Agrokimyohimoya> HAJ,CommonStock,STK,NC,1050.0,1400,1470000.0
132,2016-10-21,15:02:00,UZ7012440002 UREK,<Urganch ekskavator> AJ,CommonStock,STK,G1,5000.0,110,550000.0

In [14]:
nissdf['ISIN'] = nissdf['ISIN'].astype(str)
lastp['ISIN'] = lastp['ISIN'].astype(str)

In [17]:
merged = pd.merge(nissdf, lastp[['ISIN', 'Security_Type', 'Trade_Price', 'Date', 'Time']], on = 'ISIN', how = 'left')
merged.head()

,Category,Ticker,ISIN,Isu_Name,Listing_Date,Currency,Par_Value,Listed_Quantity,Security_Type,Trade_Price,Date,Time
0,A,HMKB,UZ7011340005 HMKB,<Hamkorbank> ATB,2007-02-06,UZS,5.0,19803920573,CommonStock,26.0,2019-01-30,13:58:28
1,A,IPKY,UZ7039920002 IPKY,AITB <Ipak Yo'li>,2007-02-22,UZS,10.0,28098500000,CommonStock,10.1,2019-01-15,13:33:57
2,A,KPBA,UZ7047440001 KPBA,<Kapitalbank> ATB,2007-04-04,UZS,950.0,101179000,CommonStock,950.0,2018-12-24,13:14:31
3,A,TNBN,UZ7035530003 TNBN,<Turonbank> ATB,2007-10-25,UZS,1700.0,445244882,CommonStock,1600.0,2018-12-13,11:09:54
4,A,TRSB,UZ7033480003 TRSB,<Trastbank> XAB,2007-11-26,UZS,1000.0,160227000,CommonStock,4000.0,2019-01-30,11:05:04

In [18]:
merged.shape

(114, 12)

In [23]:
nissdf.shape

(114, 8)

In [25]:
merged.dtypes

Category                   object
Ticker                     object
ISIN                       object
Isu_Name                   object
Listing_Date               object
Currency                   object
Par_Value                 float64
Listed_Quantity             int64
Security_Type              object
Trade_Price               float64
Date               datetime64[ns]
Time                       object
dtype: object

In [26]:
merged

,Category,Ticker,ISIN,Isu_Name,Listing_Date,Currency,Par_Value,Listed_Quantity,Security_Type,Trade_Price,Date,Time
0,A,HMKB,UZ7011340005 HMKB,<Hamkorbank> ATB,2007-02-06,UZS,5.00,19803920573,CommonStock,26.00,2019-01-30,13:58:28
1,A,IPKY,UZ7039920002 IPKY,AITB <Ipak Yo'li>,2007-02-22,UZS,10.00,28098500000,CommonStock,10.10,2019-01-15,13:33:57
2,A,KPBA,UZ7047440001 KPBA,<Kapitalbank> ATB,2007-04-04,UZS,950.00,101179000,CommonStock,950.00,2018-12-24,13:14:31
3,A,TNBN,UZ7035530003 TNBN,<Turonbank> ATB,2007-10-25,UZS,1700.00,445244882,CommonStock,1600.00,2018-12-13,11:09:54
4,A,TRSB,UZ7033480003 TRSB,<Trastbank> XAB,2007-11-26,UZS,1000.00,160227000,CommonStock,4000.00,2019-01-30,11:05:04
5,A,TKTN,UZ7009280007 TKTN,<Turkiston> XATB,2008-04-02,UZS,1000.00,104791342,CommonStock,1200.00,2019-01-17,10:56:36
6,A,OHSM,UZ7021980006 OHSM,<Ohangaronsement> AJ,2010-04-28,UZS,1000.00,4925062,CommonStock,270000.00,2019-01-29,10:36:19
7,A,QZSM,UZ7029000005 QZSM,<Qizilqumsement> AJ,2013-07-29,UZS,1570.00,447516900,CommonStock,1950.00,2019-01-30,10:02:00
8,A,INFB,UZ7055560005 INFB,ATB <InFinBank>,2014-05-27,UZS,1000.00,400000000,CommonStock,800.00,2018-08-02,10:13:08
9,A,RBQB,UZ7048610008 RBQB,<Ravnaq-bank> XATB,2014-06-26,UZS,1000.00,100000000,CommonStock,1000.00,2018-12-13,12:56:25
10,A,AABK,UZ7055790008 AABK,<Asia Alliance Bank> ATB,2014-12-12,UZS,250.00,669926405,CommonStock,260.00,2018-02-28,13:18:44
11,A,SVDB,UZ7037610001 SVDB,AT <Savdogarbank>,2014-12-23,UZS,100.00,1297000000,CommonStock,150.00,2019-01-18,13:20:22
12,A,KVTS,UZ7025770007 KVTS,<Kvarts> AJ,2015-12-04,UZS,1715.00,48224609,CommonStock,6550.00,2019-01-30,11:21:46
13,A,DAVB,UZ7050240009 DAVB,<Davr-bank> XATB,2018-11-29,UZS,5000.00,20000000,CommonStock,5000.00,2018-12-26,14:26:26
14,B,SQBN,UZ7037560008 SQBN,<O'zsanoatqurilishbank> ATB,2003-09-03,UZS,19.00,91832287892,CommonStock,16.90,2019-01-30,10:05:27
15,B,UNVB,UZ7046910004 UNVB,ATB <Universal bank>,2008-06-03,UZS,5000.00,20000000,CommonStock,5000.00,2019-01-28,14:11:20
16,B,TKVK,UZ7028090007 TKVK,ChEII <Toshkentvino kombinati> AJ,2012-10-02,UZS,4000.00,1870540,CommonStock,180000.00,2019-01-29,11:17:46
17,B,BIOK,UZ7025870005 BIOK,<Biokimyo> AJ,2013-06-21,UZS,3350.00,2856640,CommonStock,16200.00,2019-01-30,11:06:36
18,B,ALSM,UZ7045320007 ALSM,<Alskom> SK AJ,2014-01-06,UZS,1380.00,10882358,CommonStock,1670.00,2019-01-24,13:19:20
19,B,CBSK,UZ7038380000 CBSK,<Chilonzor buyum savdo kompleksi> AJ,2014-05-15,UZS,10.00,2929305573,CommonStock,28.00,2019-01-30,12:05:29
20,B,URTS,UZ7043200003 URTS,<O'zRTXB> AJ,2014-12-25,UZS,630.00,24986140,CommonStock,5999.00,2019-01-30,10:57:29
21,B,KASU,UZ7028660007 KASU,<Kapital sug'urta> AJ,2015-01-19,UZS,1.00,14000000000,CommonStock,2.95,2019-01-28,10:51:52
22,B,UZIR,UZ7052260005 UZIR,<O'zbekko'mir> AJ,2017-09-11,UZS,1000.00,38417197,CommonStock,3000.00,2019-01-30,12:44:17
23,B,SAEP,UZ7005900004 SAEP,<SAESP> AJ,2018-09-10,UZS,1000.00,2375280,NaN,NaN,NaT,NaN
24,C,AGBA,UZ7001560000 AGBA,<Agrobank> ATB,2003-09-06,UZS,1168.00,1851351565,CommonStock,1050.00,2019-01-30,10:57:17
25,C,IPTB,UZ7054570005 IPTB,<Ipoteka-bank> ATIB,2003-11-14,UZS,1.00,866012602136,CommonStock,0.99,2019-01-30,10:51:07
26,C,KKBN,UZ7018790004 KKBN,ATB <Qishloq qurilish bank>,2003-12-05,UZS,119.25,9003181987,CommonStock,140.00,2019-01-29,12:04:45
27,C,ALKB,UZ7044760005 ALKB,AT <Aloqabank>,2007-05-15,UZS,121.00,7287657194,CommonStock,225.00,2019-01-29,11:08:05
28,C,MCBA,UZ7015230004 MCBA,<Mikrokreditbank> ATB,2008-02-12,UZS,1068.00,1118015992,CommonStock,855.00,2019-01-21,12:25:23
29,C,UZMK,UZ7021720006 UZMK,<O'zmetkombinat> AJ,2010-04-12,UZS,5000.00,43322393,CommonStock,15760.00,2018-11-13,10:02:00
...,...,...,...,...,...,...,...,...,...,...,...,...
84,C,MIBK,UZ7056430018 MIBK,<Madad Invest Bank> ATB,2017-12-15,UZS,5000.00,20000000,CommonStock,5000.00,2018-08-28,13:30:00
85,C,SRVI,UZ7034010007 SRVI,<Sirdaryo vino> AJ,2017-12-21,UZS,650.00,3933566,CommonStock,650.00,2018-11-05,10:56:48
86,C,UNSU,UZ7055380008 UNSU,<Universal Sug'urta> AJ,2017-12-28,UZS,0.01,2070566000000,CommonStock,0.01,2018-04-02,10:38:50
87,C,UZHM,UZ7016400002 UZHM,<O'ZBEKKIMYOMASH ZAVODI> AJ,2018-02-21,UZS,751.00,14018940,CommonStock,1100.00,2018-12-10,14:00:47
88,C,SIRG,UZ7029920004 SIRG,<Simurg> AJ,2018-03-14,UZS,500.00,1374753,CommonStock,2304.00,2018-03-14,11:39:29
89,C,JOPT,UZ7010780003 JOPT,<Jondor paxta tozalash> AJ,2018-04-13,UZS,1000.00,8344640,CommonStock,1100.00,2018-04-18,10:25:42
90,C,JASM,UZ7012450001 JASM,<JSM> AJ,2018-05-21,UZS,1000.00,967500,CommonStock,11000.00,2019-01-29,13:19:44
91,C,XODM,UZ7024760009 XODM,<Xorazmdonmaxsulotlari> AJ,2018-06-19,UZS,100.00,21046532,CommonStock,250.00,2018-11-08,10:35:51
92,C,BODO,UZ7028200002 BODO,<Bogot-don> AJ,2018-06-21,UZS,800.00,2418148,CommonStock,800.00,2018-12-19,10:25:42
93,C,SILK,UZ7056570011 SILK,<SILK CAPITAL> AJ XK,2018-07-18,UZS,1000.00,2911000,CommonStock,1100.00,2018-12-17,13:33:44
94,C,UZSA,UZ7042140002 UZSA,<O'zbekiston shampani> AJ,2018-07-25,UZS,4000.00,338114,CommonStock,4485.00,2018-07-26,12:02:40
95,C,SODM,UZ7027940004 SODM,<Shovot don mahsulotlari> AJ,2018-07-26,UZS,100.00,9675922,CommonStock,300.00,2018-11-15,13:30:21
96,C,UZBN,UZ7055320004 UZBN,<O'zburg'uneftgaz> AJ,2018-08-10,UZS,1000.00,62106471,NaN,NaN,NaT,NaN
97,C,MSBU,UZ7015030008 MSBU,<Mulk-Sarmoya BU> AJ,2018-11-07,UZS,512.00,1828622,CommonStock,515.00,2019-01-25,10:48:50
98,C,ALLS,UZ7055590002 ALLS,<Alliance-Leasing> AJ,2018-11-13,UZS,300.00,33670000,CommonStock,999.00,2019-01-28,10:46:30
99,C,JIAZ,UZ7055840001 JIAZ,<Jizzax akkumulyator zavodi> AJ,2018-12-07,UZS,1012.67,74549895,NaN,NaN,NaT,NaN
100,P,ALPA,UZ7018610004 ALPA,QK <Agalyk-Lohmann-Parranda> AJ,2015-03-13,UZS,3000.00,408590,NaN,NaN,NaT,NaN
101,P,ANPA,UZ7019750007 ANPA,XS <ANGREN PACK> AJ,2015-06-17,UZS,1500.00,406392,CommonStock,10000.00,2018-06-05,10:59:57
102,P,XOSQ,UZ7053370001 XOSQ,<Xorazmsuvqurilish> AJ,2015-09-09,UZS,1000.00,606121,NaN,NaN,NaT,NaN
103,P,BCSD,UZ7000560001 BCSD,QK <Biznes Centr Samarkand> AJ,2015-09-09,UZS,5000.00,40000,NaN,NaN,NaT,NaN
104,P,GAVT,UZ7026050003 GAVT,<Gazavtomatika> AJ,2015-10-19,UZS,100.00,638714,NaN,NaN,NaT,NaN
105,P,BGSS,UZ7050560000 BGSS,<Buxoro go'sht-sut savdo> AJ UHB,2015-11-02,UZS,1733.00,553280,NaN,NaN,NaT,NaN
106,P,SOOM,UZ7050670007 SOOM,<Surxondaryo oziq-ovqat mollari> AJ UHB,2015-11-02,UZS,1850.80,325000,CommonStock,7835.00,2018-08-14,12:11:38
107,P,KNIT,UZ7054370000 KNIT,<QNGIT> AJ,2015-11-11,UZS,3000.00,252358,CommonStock,3300.00,2016-11-18,10:34:57
108,P,FGSS,UZ7051770004 FGSS,<Farg'ona go'sht-sut savdo> AJ MSMTvaG'K,2015-11-13,UZS,2337.00,580000,CommonStock,22100.00,2017-01-25,10:40:07
109,P,BUPD,UZ7018260008 BUPD,<Buxoroparranda> AJ,2015-12-04,UZS,500.00,1269828,NaN,NaN,NaT,NaN
110,P,TOOS,UZ7052380001 TOOS,<Toshkent - Osiyo> AJ,2015-12-25,UZS,100.00,19386901,CommonStock,542.00,2017-10-09,12:34:39
111,P,UZEK,UZ7053530000 UZEK,<O'zbekekspertiza> AJ,2016-03-30,UZS,1622.00,1596540,CommonStock,1622.00,2019-01-29,13:24:11
112,P,MATA,UZ7047670003 MATA,<Matbuot tarqatuvchi> AK,2016-05-27,UZS,4000.00,1000000,CommonStock,5000.00,2018-10-03,12:10:48
113,P,SVAH,UZ7048180002 SVAH,Samarqand viloyati <Agrokimyohimoya> HAJ,2018-11-13,UZS,2400.00,743433,NaN,NaN,NaT,NaN

In [27]:
merged.isnull().sum()

Category            0
Ticker              0
ISIN                0
Isu_Name            0
Listing_Date        0
Currency            0
Par_Value           0
Listed_Quantity     0
Security_Type      15
Trade_Price        15
Date               15
Time               15
dtype: int64

In [28]:
merged['Market_Cap'] = np.where(merged['Trade_Price'].isnull(), 
                            merged.Listed_Quantity * merged.Par_Value, 
                            merged.Listed_Quantity * merged.Trade_Price)
merged.head()

,Category,Ticker,ISIN,Isu_Name,Listing_Date,Currency,Par_Value,Listed_Quantity,Security_Type,Trade_Price,Date,Time,Market_Cap
0,A,HMKB,UZ7011340005 HMKB,<Hamkorbank> ATB,2007-02-06,UZS,5.0,19803920573,CommonStock,26.0,2019-01-30,13:58:28,5.149019e+11
1,A,IPKY,UZ7039920002 IPKY,AITB <Ipak Yo'li>,2007-02-22,UZS,10.0,28098500000,CommonStock,10.1,2019-01-15,13:33:57,2.837948e+11
2,A,KPBA,UZ7047440001 KPBA,<Kapitalbank> ATB,2007-04-04,UZS,950.0,101179000,CommonStock,950.0,2018-12-24,13:14:31,9.612005e+10
3,A,TNBN,UZ7035530003 TNBN,<Turonbank> ATB,2007-10-25,UZS,1700.0,445244882,CommonStock,1600.0,2018-12-13,11:09:54,7.123918e+11
4,A,TRSB,UZ7033480003 TRSB,<Trastbank> XAB,2007-11-26,UZS,1000.0,160227000,CommonStock,4000.0,2019-01-30,11:05:04,6.409080e+11

In [29]:
merged.to_csv(r'C:\Users\Alisher\Desktop\mgd.csv')